name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # - name: Deploy to ECS Express Mode
      #   timeout-minutes: 1
      #   continue-on-error: true
      #   uses: aws-actions/amazon-ecs-deploy-express-service@v1
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      #   with:
      #     service-name: ${{ vars.ECS_SERVICE }}
      #     image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
      #     execution-role-arn: ${{ secrets.ECS_EXECUTION_ROLE_ARN }}
      #     infrastructure-role-arn: ${{ secrets.ECS_INFRASTRUCTURE_ROLE_ARN }}
      #     cluster: ${{ vars.ECS_CLUSTER }}

      - name: Deploy to ECS Express Mode
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ vars.AWS_REGION }}
          echo "Deployment triggered successfully."
